package com.expmatik.backend.notification;

public enum NotificationType {
    PRODUCT_SHORTAGE, EXPIRED_PRODUCT, ASSIGNED_RESTOCKING, COMPLETED_RESTOCKING, INVENTORY_STOCK_LOW, SALE_SUCCESS,SALE_FAILURE;
}
