package com.expmatik.backend.notification;

public enum NotificationType {
    PRODUCT_LOW_STOCK,PRODUCT_OUT_OF_STOCK,EXPIRATION_WARNING,PRODUCT_EXPIRED, ASSIGNED_RESTOCKING, DELAYED_MAINTENANCE, COMPLETED_RESTOCKING, INVENTORY_STOCK_LOW,INVENTORY_OUT_OF_STOCK,FAILURE_SALE;
}
