spring:
  application:
    name: vending-backend
  config:
    import: optional:file:./backend/.env[.properties],optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload:
    dir: ${UPLOAD_DIR:uploads}
  prediction-seeder:
    enabled: ${PREDICTION_SEEDER_ENABLED:false}
jwt:
  expiration-at: ${JWT_EXPIRATION_AT:86400000}
  expiration-rt: ${JWT_EXPIRATION_RT:604800000}
  secret-key: ${JWT_SECRET_KEY:bient7UNdfnJQwSCieEN3mH/6APi7s7pyWwCmwWyHQY=}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
